/**
 * Where files (photos, signatures, reports) are kept. Business logic stores
 * only the storage key; the backend behind it is chosen by STORAGE_DRIVER
 * (local disk now; an S3-compatible driver can implement the same interface).
 */
export interface ObjectStorage {
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

/** Keys are generated by the API: lower-case path segments, no "..", no leading "/". */
const KEY = /^[a-z0-9][a-z0-9_-]*(\/[a-z0-9][a-z0-9_.-]*)*$/;

export function assertValidKey(key: string): void {
  if (!KEY.test(key) || key.includes('..') || key.length > 255) throw new Error(`Invalid storage key: ${key}`);
}

export class StorageNotFoundError extends Error {
  constructor(key: string) {
    super(`No stored object for key ${key}`);
    this.name = 'StorageNotFoundError';
  }
}
