// AUTO-GENERATED by scripts/gen-db-types.mjs from the Supabase migrations.
// Do not edit by hand. Regenerate with: pnpm db:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: number;
          actor_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: never;
          actor_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: never;
          actor_id?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'audit_logs_actor_id_fkey';
            columns: ['actor_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      battery_readings: {
        Row: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          battery_voltage_v: number | null;
          capacity_ah: number | null;
          string_count: number | null;
          physical_damage_found: boolean | null;
          water_top_up_required: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          battery_voltage_v?: number | null;
          capacity_ah?: number | null;
          string_count?: number | null;
          physical_damage_found?: boolean | null;
          water_top_up_required?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          visit_id?: string;
          site_id?: string;
          recorded_at?: string;
          battery_voltage_v?: number | null;
          capacity_ah?: number | null;
          string_count?: number | null;
          physical_damage_found?: boolean | null;
          water_top_up_required?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'battery_readings_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'battery_readings_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: true;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      clusters: {
        Row: {
          id: string;
          region_id: string;
          code: string;
          name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          region_id: string;
          code: string;
          name: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          region_id?: string;
          code?: string;
          name?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'clusters_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'clusters_region_id_fkey';
            columns: ['region_id'];
            isOneToOne: false;
            referencedRelation: 'regions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'clusters_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      corrective_action_updates: {
        Row: {
          id: string;
          corrective_action_id: string;
          author_id: string;
          from_status: Database['public']['Enums']['corrective_action_status'] | null;
          to_status: Database['public']['Enums']['corrective_action_status'] | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          corrective_action_id: string;
          author_id?: string;
          from_status?: Database['public']['Enums']['corrective_action_status'] | null;
          to_status?: Database['public']['Enums']['corrective_action_status'] | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          corrective_action_id?: string;
          author_id?: string;
          from_status?: Database['public']['Enums']['corrective_action_status'] | null;
          to_status?: Database['public']['Enums']['corrective_action_status'] | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'corrective_action_updates_author_id_fkey';
            columns: ['author_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'corrective_action_updates_corrective_action_id_fkey';
            columns: ['corrective_action_id'];
            isOneToOne: false;
            referencedRelation: 'corrective_actions';
            referencedColumns: ['id'];
          },
        ];
      };
      corrective_actions: {
        Row: {
          id: string;
          action_number: string;
          failure_id: string | null;
          site_id: string;
          visit_id: string | null;
          category: Database['public']['Enums']['pm_category'];
          description: string;
          priority: Database['public']['Enums']['priority_level'];
          assigned_to: string | null;
          assigned_by: string | null;
          assigned_at: string | null;
          due_date: string | null;
          status: Database['public']['Enums']['corrective_action_status'];
          resolution: string | null;
          completed_at: string | null;
          verified_by: string | null;
          verified_at: string | null;
          closed_at: string | null;
          client_updated_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          action_number?: string;
          failure_id?: string | null;
          site_id: string;
          visit_id?: string | null;
          category: Database['public']['Enums']['pm_category'];
          description: string;
          priority?: Database['public']['Enums']['priority_level'];
          assigned_to?: string | null;
          assigned_by?: string | null;
          assigned_at?: string | null;
          due_date?: string | null;
          status?: Database['public']['Enums']['corrective_action_status'];
          resolution?: string | null;
          completed_at?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          closed_at?: string | null;
          client_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          action_number?: string;
          failure_id?: string | null;
          site_id?: string;
          visit_id?: string | null;
          category?: Database['public']['Enums']['pm_category'];
          description?: string;
          priority?: Database['public']['Enums']['priority_level'];
          assigned_to?: string | null;
          assigned_by?: string | null;
          assigned_at?: string | null;
          due_date?: string | null;
          status?: Database['public']['Enums']['corrective_action_status'];
          resolution?: string | null;
          completed_at?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          closed_at?: string | null;
          client_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'corrective_actions_assigned_by_fkey';
            columns: ['assigned_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'corrective_actions_assigned_to_fkey';
            columns: ['assigned_to'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'corrective_actions_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'corrective_actions_failure_id_fkey';
            columns: ['failure_id'];
            isOneToOne: false;
            referencedRelation: 'failures';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'corrective_actions_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'corrective_actions_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'corrective_actions_verified_by_fkey';
            columns: ['verified_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'corrective_actions_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: false;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      counties: {
        Row: {
          id: string;
          cluster_id: string;
          code: string;
          name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          cluster_id: string;
          code: string;
          name: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          cluster_id?: string;
          code?: string;
          name?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'counties_cluster_id_fkey';
            columns: ['cluster_id'];
            isOneToOne: false;
            referencedRelation: 'clusters';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'counties_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'counties_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      dc_phase_currents: {
        Row: {
          id: string;
          visit_id: string;
          site_id: string;
          phase_number: number;
          amp_value: number | null;
          unit: string;
          photo_id: string | null;
          comment: string | null;
          recorded_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          visit_id: string;
          site_id: string;
          phase_number: number;
          amp_value?: number | null;
          unit?: string;
          photo_id?: string | null;
          comment?: string | null;
          recorded_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          visit_id?: string;
          site_id?: string;
          phase_number?: number;
          amp_value?: number | null;
          unit?: string;
          photo_id?: string | null;
          comment?: string | null;
          recorded_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'dc_phase_currents_photo_fkey';
            columns: ['photo_id'];
            isOneToOne: false;
            referencedRelation: 'pm_photos';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'dc_phase_currents_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'dc_phase_currents_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: false;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      dc_readings: {
        Row: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          rectifier_voltage_v: number | null;
          load_current_a: number | null;
          rectifier_module_count: number | null;
          dc_modules_installed: number | null;
          dc_modules_operational: number | null;
          controller_model: string | null;
          dc_power_kw: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          rectifier_voltage_v?: number | null;
          load_current_a?: number | null;
          rectifier_module_count?: number | null;
          dc_modules_installed?: number | null;
          dc_modules_operational?: number | null;
          controller_model?: string | null;
          dc_power_kw?: never;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          visit_id?: string;
          site_id?: string;
          recorded_at?: string;
          rectifier_voltage_v?: number | null;
          load_current_a?: number | null;
          rectifier_module_count?: number | null;
          dc_modules_installed?: number | null;
          dc_modules_operational?: number | null;
          controller_model?: string | null;
          dc_power_kw?: never;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'dc_readings_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'dc_readings_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: true;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      earthing_readings: {
        Row: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          inspected: boolean | null;
          earth_cable_connected: boolean | null;
          free_from_corrosion: boolean | null;
          pit_condition_acceptable: boolean | null;
          abnormalities_found: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          inspected?: boolean | null;
          earth_cable_connected?: boolean | null;
          free_from_corrosion?: boolean | null;
          pit_condition_acceptable?: boolean | null;
          abnormalities_found?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          visit_id?: string;
          site_id?: string;
          recorded_at?: string;
          inspected?: boolean | null;
          earth_cable_connected?: boolean | null;
          free_from_corrosion?: boolean | null;
          pit_condition_acceptable?: boolean | null;
          abnormalities_found?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'earthing_readings_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'earthing_readings_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: true;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      equipment: {
        Row: {
          id: string;
          site_id: string;
          category: Database['public']['Enums']['pm_category'];
          equipment_type: string;
          manufacturer: string | null;
          model: string | null;
          serial_number: string | null;
          capacity: number | null;
          capacity_unit: string | null;
          installed_on: string | null;
          status: string;
          notes: string | null;
          metadata: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          category: Database['public']['Enums']['pm_category'];
          equipment_type: string;
          manufacturer?: string | null;
          model?: string | null;
          serial_number?: string | null;
          capacity?: number | null;
          capacity_unit?: string | null;
          installed_on?: string | null;
          status?: string;
          notes?: string | null;
          metadata?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          category?: Database['public']['Enums']['pm_category'];
          equipment_type?: string;
          manufacturer?: string | null;
          model?: string | null;
          serial_number?: string | null;
          capacity?: number | null;
          capacity_unit?: string | null;
          installed_on?: string | null;
          status?: string;
          notes?: string | null;
          metadata?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'equipment_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'equipment_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'equipment_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      equipment_history: {
        Row: {
          id: string;
          equipment_id: string;
          event_type: string;
          event_at: string;
          visit_id: string | null;
          corrective_action_id: string | null;
          notes: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          equipment_id: string;
          event_type: string;
          event_at?: string;
          visit_id?: string | null;
          corrective_action_id?: string | null;
          notes?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          equipment_id?: string;
          event_type?: string;
          event_at?: string;
          visit_id?: string | null;
          corrective_action_id?: string | null;
          notes?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'equipment_history_corrective_action_id_fkey';
            columns: ['corrective_action_id'];
            isOneToOne: false;
            referencedRelation: 'corrective_actions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'equipment_history_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'equipment_history_equipment_id_fkey';
            columns: ['equipment_id'];
            isOneToOne: false;
            referencedRelation: 'equipment';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'equipment_history_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'equipment_history_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: false;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      failures: {
        Row: {
          id: string;
          failure_number: string;
          source: Database['public']['Enums']['failure_source'];
          site_id: string;
          visit_id: string | null;
          section_id: string | null;
          checklist_item_id: string | null;
          response_id: string | null;
          category: Database['public']['Enums']['pm_category'];
          technician_id: string | null;
          detected_at: string;
          description: string;
          severity: Database['public']['Enums']['severity_level'];
          status: Database['public']['Enums']['failure_status'];
          resolved_at: string | null;
          verified_by: string | null;
          verified_at: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          failure_number?: string;
          source?: Database['public']['Enums']['failure_source'];
          site_id: string;
          visit_id?: string | null;
          section_id?: string | null;
          checklist_item_id?: string | null;
          response_id?: string | null;
          category: Database['public']['Enums']['pm_category'];
          technician_id?: string | null;
          detected_at?: string;
          description: string;
          severity?: Database['public']['Enums']['severity_level'];
          status?: Database['public']['Enums']['failure_status'];
          resolved_at?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          failure_number?: string;
          source?: Database['public']['Enums']['failure_source'];
          site_id?: string;
          visit_id?: string | null;
          section_id?: string | null;
          checklist_item_id?: string | null;
          response_id?: string | null;
          category?: Database['public']['Enums']['pm_category'];
          technician_id?: string | null;
          detected_at?: string;
          description?: string;
          severity?: Database['public']['Enums']['severity_level'];
          status?: Database['public']['Enums']['failure_status'];
          resolved_at?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'failures_checklist_item_id_fkey';
            columns: ['checklist_item_id'];
            isOneToOne: false;
            referencedRelation: 'pm_checklist_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'failures_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'failures_response_id_fkey';
            columns: ['response_id'];
            isOneToOne: false;
            referencedRelation: 'pm_responses';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'failures_section_id_fkey';
            columns: ['section_id'];
            isOneToOne: false;
            referencedRelation: 'pm_sections';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'failures_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'failures_technician_id_fkey';
            columns: ['technician_id'];
            isOneToOne: false;
            referencedRelation: 'technicians';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'failures_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'failures_verified_by_fkey';
            columns: ['verified_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'failures_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: false;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      generator_readings: {
        Row: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          running_hours: number | null;
          oil_pressure_bar: number | null;
          fuel_level_pct: number | null;
          generator_kva: number | null;
          engine_oil_changed: boolean | null;
          fuel_filter_changed: boolean | null;
          oil_filter_changed: boolean | null;
          requires_service: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          running_hours?: number | null;
          oil_pressure_bar?: number | null;
          fuel_level_pct?: number | null;
          generator_kva?: number | null;
          engine_oil_changed?: boolean | null;
          fuel_filter_changed?: boolean | null;
          oil_filter_changed?: boolean | null;
          requires_service?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          visit_id?: string;
          site_id?: string;
          recorded_at?: string;
          running_hours?: number | null;
          oil_pressure_bar?: number | null;
          fuel_level_pct?: number | null;
          generator_kva?: number | null;
          engine_oil_changed?: boolean | null;
          fuel_filter_changed?: boolean | null;
          oil_filter_changed?: boolean | null;
          requires_service?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'generator_readings_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'generator_readings_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: true;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      notifications: {
        Row: {
          id: string;
          recipient_id: string;
          type: Database['public']['Enums']['notification_type'];
          title: string;
          body: string | null;
          entity_type: string | null;
          entity_id: string | null;
          read_at: string | null;
          push_sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipient_id: string;
          type: Database['public']['Enums']['notification_type'];
          title: string;
          body?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          read_at?: string | null;
          push_sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipient_id?: string;
          type?: Database['public']['Enums']['notification_type'];
          title?: string;
          body?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          read_at?: string | null;
          push_sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'notifications_recipient_id_fkey';
            columns: ['recipient_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_checklist_items: {
        Row: {
          id: string;
          section_id: string;
          code: string;
          prompt: string;
          help_text: string | null;
          response_type: Database['public']['Enums']['response_type'];
          options: Json;
          allow_not_applicable: boolean;
          is_required: boolean;
          unit: string | null;
          min_value: number | null;
          max_value: number | null;
          creates_failure_on_no: boolean;
          creates_failure_on_yes: boolean;
          failure_severity: Database['public']['Enums']['severity_level'];
          requires_photo_on_failure: boolean;
          requires_comment_on_failure: boolean;
          requires_photo_on_answer: Database['public']['Enums']['yes_no_na'][];
          requires_comment_on_answer: Database['public']['Enums']['yes_no_na'][];
          photo_instructions: string | null;
          metadata: Json;
          analytics_key: string | null;
          sort_order: number;
          is_active: boolean;
          deactivated_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          section_id: string;
          code: string;
          prompt: string;
          help_text?: string | null;
          response_type?: Database['public']['Enums']['response_type'];
          options?: Json;
          allow_not_applicable?: boolean;
          is_required?: boolean;
          unit?: string | null;
          min_value?: number | null;
          max_value?: number | null;
          creates_failure_on_no?: boolean;
          creates_failure_on_yes?: boolean;
          failure_severity?: Database['public']['Enums']['severity_level'];
          requires_photo_on_failure?: boolean;
          requires_comment_on_failure?: boolean;
          requires_photo_on_answer?: Database['public']['Enums']['yes_no_na'][];
          requires_comment_on_answer?: Database['public']['Enums']['yes_no_na'][];
          photo_instructions?: string | null;
          metadata?: Json;
          analytics_key?: string | null;
          sort_order?: number;
          is_active?: boolean;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          section_id?: string;
          code?: string;
          prompt?: string;
          help_text?: string | null;
          response_type?: Database['public']['Enums']['response_type'];
          options?: Json;
          allow_not_applicable?: boolean;
          is_required?: boolean;
          unit?: string | null;
          min_value?: number | null;
          max_value?: number | null;
          creates_failure_on_no?: boolean;
          creates_failure_on_yes?: boolean;
          failure_severity?: Database['public']['Enums']['severity_level'];
          requires_photo_on_failure?: boolean;
          requires_comment_on_failure?: boolean;
          requires_photo_on_answer?: Database['public']['Enums']['yes_no_na'][];
          requires_comment_on_answer?: Database['public']['Enums']['yes_no_na'][];
          photo_instructions?: string | null;
          metadata?: Json;
          analytics_key?: string | null;
          sort_order?: number;
          is_active?: boolean;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_checklist_items_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_checklist_items_section_id_fkey';
            columns: ['section_id'];
            isOneToOne: false;
            referencedRelation: 'pm_sections';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_checklist_items_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_consistency_rules: {
        Row: {
          id: string;
          lhs_key: string;
          operator: string;
          rhs_key: string;
          message: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          lhs_key: string;
          operator: string;
          rhs_key: string;
          message: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          lhs_key?: string;
          operator?: string;
          rhs_key?: string;
          message?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_consistency_rules_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_consistency_rules_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_photos: {
        Row: {
          id: string;
          site_id: string;
          visit_id: string | null;
          section_id: string | null;
          checklist_item_id: string | null;
          reading_field_id: string | null;
          failure_id: string | null;
          corrective_action_id: string | null;
          bucket: string;
          file_path: string;
          thumbnail_path: string | null;
          mime_type: string | null;
          size_bytes: number | null;
          width: number | null;
          height: number | null;
          caption: string | null;
          latitude: number | null;
          longitude: number | null;
          taken_at: string;
          uploaded_at: string | null;
          uploaded_by: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          visit_id?: string | null;
          section_id?: string | null;
          checklist_item_id?: string | null;
          reading_field_id?: string | null;
          failure_id?: string | null;
          corrective_action_id?: string | null;
          bucket?: string;
          file_path: string;
          thumbnail_path?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          caption?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          taken_at: string;
          uploaded_at?: string | null;
          uploaded_by?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          visit_id?: string | null;
          section_id?: string | null;
          checklist_item_id?: string | null;
          reading_field_id?: string | null;
          failure_id?: string | null;
          corrective_action_id?: string | null;
          bucket?: string;
          file_path?: string;
          thumbnail_path?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          caption?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          taken_at?: string;
          uploaded_at?: string | null;
          uploaded_by?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_photos_checklist_item_id_fkey';
            columns: ['checklist_item_id'];
            isOneToOne: false;
            referencedRelation: 'pm_checklist_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_photos_corrective_action_id_fkey';
            columns: ['corrective_action_id'];
            isOneToOne: false;
            referencedRelation: 'corrective_actions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_photos_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_photos_failure_id_fkey';
            columns: ['failure_id'];
            isOneToOne: false;
            referencedRelation: 'failures';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_photos_reading_field_id_fkey';
            columns: ['reading_field_id'];
            isOneToOne: false;
            referencedRelation: 'pm_reading_fields';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_photos_section_id_fkey';
            columns: ['section_id'];
            isOneToOne: false;
            referencedRelation: 'pm_sections';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_photos_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_photos_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_photos_uploaded_by_fkey';
            columns: ['uploaded_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_photos_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: false;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_reading_fields: {
        Row: {
          id: string;
          section_id: string;
          code: string;
          label: string;
          value_type: Database['public']['Enums']['response_type'];
          unit: string | null;
          is_integer: boolean;
          min_value: number | null;
          max_value: number | null;
          options: Json;
          is_required: boolean;
          help_text: string | null;
          analytics_key: string | null;
          sort_order: number;
          is_active: boolean;
          deactivated_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          section_id: string;
          code: string;
          label: string;
          value_type?: Database['public']['Enums']['response_type'];
          unit?: string | null;
          is_integer?: boolean;
          min_value?: number | null;
          max_value?: number | null;
          options?: Json;
          is_required?: boolean;
          help_text?: string | null;
          analytics_key?: string | null;
          sort_order?: number;
          is_active?: boolean;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          section_id?: string;
          code?: string;
          label?: string;
          value_type?: Database['public']['Enums']['response_type'];
          unit?: string | null;
          is_integer?: boolean;
          min_value?: number | null;
          max_value?: number | null;
          options?: Json;
          is_required?: boolean;
          help_text?: string | null;
          analytics_key?: string | null;
          sort_order?: number;
          is_active?: boolean;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_reading_fields_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_reading_fields_section_id_fkey';
            columns: ['section_id'];
            isOneToOne: false;
            referencedRelation: 'pm_sections';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_reading_fields_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_readings: {
        Row: {
          id: string;
          visit_id: string;
          reading_field_id: string;
          numeric_value: number | null;
          text_value: string | null;
          unit_snapshot: string | null;
          label_snapshot: string;
          captured_at: string | null;
          client_updated_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          visit_id: string;
          reading_field_id: string;
          numeric_value?: number | null;
          text_value?: string | null;
          unit_snapshot?: string | null;
          label_snapshot: string;
          captured_at?: string | null;
          client_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          visit_id?: string;
          reading_field_id?: string;
          numeric_value?: number | null;
          text_value?: string | null;
          unit_snapshot?: string | null;
          label_snapshot?: string;
          captured_at?: string | null;
          client_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_readings_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_readings_reading_field_id_fkey';
            columns: ['reading_field_id'];
            isOneToOne: false;
            referencedRelation: 'pm_reading_fields';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_readings_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_readings_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: false;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_responses: {
        Row: {
          id: string;
          visit_id: string;
          checklist_item_id: string;
          answer: Database['public']['Enums']['yes_no_na'] | null;
          numeric_value: number | null;
          text_value: string | null;
          selected_options: string[] | null;
          date_value: string | null;
          datetime_value: string | null;
          comment: string | null;
          is_failure: boolean;
          prompt_snapshot: string;
          unit_snapshot: string | null;
          answered_at: string | null;
          answered_by: string | null;
          client_updated_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          visit_id: string;
          checklist_item_id: string;
          answer?: Database['public']['Enums']['yes_no_na'] | null;
          numeric_value?: number | null;
          text_value?: string | null;
          selected_options?: string[] | null;
          date_value?: string | null;
          datetime_value?: string | null;
          comment?: string | null;
          is_failure?: boolean;
          prompt_snapshot: string;
          unit_snapshot?: string | null;
          answered_at?: string | null;
          answered_by?: string | null;
          client_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          visit_id?: string;
          checklist_item_id?: string;
          answer?: Database['public']['Enums']['yes_no_na'] | null;
          numeric_value?: number | null;
          text_value?: string | null;
          selected_options?: string[] | null;
          date_value?: string | null;
          datetime_value?: string | null;
          comment?: string | null;
          is_failure?: boolean;
          prompt_snapshot?: string;
          unit_snapshot?: string | null;
          answered_at?: string | null;
          answered_by?: string | null;
          client_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_responses_answered_by_fkey';
            columns: ['answered_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_responses_checklist_item_id_fkey';
            columns: ['checklist_item_id'];
            isOneToOne: false;
            referencedRelation: 'pm_checklist_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_responses_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_responses_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_responses_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: false;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_schedules: {
        Row: {
          id: string;
          site_id: string;
          template_id: string;
          technician_id: string | null;
          supervisor_id: string | null;
          frequency: Database['public']['Enums']['pm_frequency'];
          scheduled_date: string;
          due_date: string;
          status: Database['public']['Enums']['pm_status'];
          priority: Database['public']['Enums']['priority_level'];
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          template_id: string;
          technician_id?: string | null;
          supervisor_id?: string | null;
          frequency?: Database['public']['Enums']['pm_frequency'];
          scheduled_date: string;
          due_date: string;
          status?: Database['public']['Enums']['pm_status'];
          priority?: Database['public']['Enums']['priority_level'];
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          template_id?: string;
          technician_id?: string | null;
          supervisor_id?: string | null;
          frequency?: Database['public']['Enums']['pm_frequency'];
          scheduled_date?: string;
          due_date?: string;
          status?: Database['public']['Enums']['pm_status'];
          priority?: Database['public']['Enums']['priority_level'];
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_schedules_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_schedules_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_schedules_supervisor_id_fkey';
            columns: ['supervisor_id'];
            isOneToOne: false;
            referencedRelation: 'supervisors';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_schedules_technician_id_fkey';
            columns: ['technician_id'];
            isOneToOne: false;
            referencedRelation: 'technicians';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_schedules_template_id_fkey';
            columns: ['template_id'];
            isOneToOne: false;
            referencedRelation: 'pm_templates';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_schedules_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_sections: {
        Row: {
          id: string;
          template_id: string;
          code: string;
          name: string;
          category: Database['public']['Enums']['pm_category'];
          sort_order: number;
          description: string | null;
          allow_not_applicable: boolean;
          applicable_site_flag: string | null;
          is_active: boolean;
          deactivated_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          template_id: string;
          code: string;
          name: string;
          category: Database['public']['Enums']['pm_category'];
          sort_order?: number;
          description?: string | null;
          allow_not_applicable?: boolean;
          applicable_site_flag?: string | null;
          is_active?: boolean;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          template_id?: string;
          code?: string;
          name?: string;
          category?: Database['public']['Enums']['pm_category'];
          sort_order?: number;
          description?: string | null;
          allow_not_applicable?: boolean;
          applicable_site_flag?: string | null;
          is_active?: boolean;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_sections_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_sections_template_id_fkey';
            columns: ['template_id'];
            isOneToOne: false;
            referencedRelation: 'pm_templates';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_sections_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_templates: {
        Row: {
          id: string;
          code: string;
          name: string;
          version: number;
          status: Database['public']['Enums']['template_status'];
          description: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          version?: number;
          status?: Database['public']['Enums']['template_status'];
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          version?: number;
          status?: Database['public']['Enums']['template_status'];
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_templates_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_templates_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      pm_visits: {
        Row: {
          id: string;
          schedule_id: string | null;
          site_id: string;
          template_id: string;
          technician_id: string;
          supervisor_id: string | null;
          status: Database['public']['Enums']['pm_status'];
          started_at: string | null;
          ended_at: string | null;
          submitted_at: string | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy_m: number | null;
          gps_captured_at: string | null;
          gps_distance_m: number | null;
          gps_radius_m: number | null;
          gps_status: Database['public']['Enums']['gps_status'] | null;
          geofence_mode: Database['public']['Enums']['geofence_mode'] | null;
          outside_radius_reason: string | null;
          completion_pct: number;
          failure_count: number;
          not_applicable_sections: string[];
          overall_comments: string | null;
          is_demo: boolean;
          technician_signature_path: string | null;
          technician_signed_at: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_comments: string | null;
          device_id: string | null;
          client_created_at: string | null;
          client_updated_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          schedule_id?: string | null;
          site_id: string;
          template_id: string;
          technician_id: string;
          supervisor_id?: string | null;
          status?: Database['public']['Enums']['pm_status'];
          started_at?: string | null;
          ended_at?: string | null;
          submitted_at?: string | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy_m?: number | null;
          gps_captured_at?: string | null;
          gps_distance_m?: number | null;
          gps_radius_m?: number | null;
          gps_status?: Database['public']['Enums']['gps_status'] | null;
          geofence_mode?: Database['public']['Enums']['geofence_mode'] | null;
          outside_radius_reason?: string | null;
          completion_pct?: number;
          failure_count?: number;
          not_applicable_sections?: string[];
          overall_comments?: string | null;
          is_demo?: boolean;
          technician_signature_path?: string | null;
          technician_signed_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_comments?: string | null;
          device_id?: string | null;
          client_created_at?: string | null;
          client_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          schedule_id?: string | null;
          site_id?: string;
          template_id?: string;
          technician_id?: string;
          supervisor_id?: string | null;
          status?: Database['public']['Enums']['pm_status'];
          started_at?: string | null;
          ended_at?: string | null;
          submitted_at?: string | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy_m?: number | null;
          gps_captured_at?: string | null;
          gps_distance_m?: number | null;
          gps_radius_m?: number | null;
          gps_status?: Database['public']['Enums']['gps_status'] | null;
          geofence_mode?: Database['public']['Enums']['geofence_mode'] | null;
          outside_radius_reason?: string | null;
          completion_pct?: number;
          failure_count?: number;
          not_applicable_sections?: string[];
          overall_comments?: string | null;
          is_demo?: boolean;
          technician_signature_path?: string | null;
          technician_signed_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_comments?: string | null;
          device_id?: string | null;
          client_created_at?: string | null;
          client_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pm_visits_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_visits_reviewed_by_fkey';
            columns: ['reviewed_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_visits_schedule_id_fkey';
            columns: ['schedule_id'];
            isOneToOne: false;
            referencedRelation: 'pm_schedules';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_visits_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_visits_supervisor_id_fkey';
            columns: ['supervisor_id'];
            isOneToOne: false;
            referencedRelation: 'supervisors';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_visits_technician_id_fkey';
            columns: ['technician_id'];
            isOneToOne: false;
            referencedRelation: 'technicians';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_visits_template_id_fkey';
            columns: ['template_id'];
            isOneToOne: false;
            referencedRelation: 'pm_templates';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pm_visits_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone: string | null;
          avatar_url: string | null;
          role: Database['public']['Enums']['app_role'];
          region_id: string | null;
          is_active: boolean;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string;
          phone?: string | null;
          avatar_url?: string | null;
          role?: Database['public']['Enums']['app_role'];
          region_id?: string | null;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          phone?: string | null;
          avatar_url?: string | null;
          role?: Database['public']['Enums']['app_role'];
          region_id?: string | null;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'profiles_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'profiles_region_id_fkey';
            columns: ['region_id'];
            isOneToOne: false;
            referencedRelation: 'regions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'profiles_role_fkey';
            columns: ['role'];
            isOneToOne: false;
            referencedRelation: 'roles';
            referencedColumns: ['code'];
          },
          {
            foreignKeyName: 'profiles_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      regions: {
        Row: {
          id: string;
          code: string;
          name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'regions_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'regions_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      roles: {
        Row: {
          code: Database['public']['Enums']['app_role'];
          name: string;
          description: string;
          sort_order: number;
        };
        Insert: {
          code: Database['public']['Enums']['app_role'];
          name: string;
          description: string;
          sort_order?: number;
        };
        Update: {
          code?: Database['public']['Enums']['app_role'];
          name?: string;
          description?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      site_assignments: {
        Row: {
          id: string;
          site_id: string;
          technician_id: string;
          starts_on: string;
          ends_on: string | null;
          is_active: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          technician_id: string;
          starts_on?: string;
          ends_on?: string | null;
          is_active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          technician_id?: string;
          starts_on?: string;
          ends_on?: string | null;
          is_active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'site_assignments_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'site_assignments_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'site_assignments_technician_id_fkey';
            columns: ['technician_id'];
            isOneToOne: false;
            referencedRelation: 'technicians';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'site_assignments_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      site_documents: {
        Row: {
          id: string;
          site_id: string;
          title: string;
          document_type: string | null;
          bucket: string;
          file_path: string;
          mime_type: string | null;
          size_bytes: number | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          title: string;
          document_type?: string | null;
          bucket?: string;
          file_path: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          title?: string;
          document_type?: string | null;
          bucket?: string;
          file_path?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'site_documents_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'site_documents_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'site_documents_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      sites: {
        Row: {
          id: string;
          site_code: string;
          site_name: string;
          region_id: string;
          cluster_id: string | null;
          county_id: string | null;
          latitude: number | null;
          longitude: number | null;
          address: string | null;
          site_type: string | null;
          power_configuration: string | null;
          generator_available: boolean;
          solar_available: boolean;
          battery_available: boolean;
          grid_available: boolean;
          status: Database['public']['Enums']['site_status'];
          supervisor_id: string | null;
          geofence_radius_m: number | null;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          site_code: string;
          site_name: string;
          region_id: string;
          cluster_id?: string | null;
          county_id?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          address?: string | null;
          site_type?: string | null;
          power_configuration?: string | null;
          generator_available?: boolean;
          solar_available?: boolean;
          battery_available?: boolean;
          grid_available?: boolean;
          status?: Database['public']['Enums']['site_status'];
          supervisor_id?: string | null;
          geofence_radius_m?: number | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          site_code?: string;
          site_name?: string;
          region_id?: string;
          cluster_id?: string | null;
          county_id?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          address?: string | null;
          site_type?: string | null;
          power_configuration?: string | null;
          generator_available?: boolean;
          solar_available?: boolean;
          battery_available?: boolean;
          grid_available?: boolean;
          status?: Database['public']['Enums']['site_status'];
          supervisor_id?: string | null;
          geofence_radius_m?: number | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'sites_cluster_id_fkey';
            columns: ['cluster_id'];
            isOneToOne: false;
            referencedRelation: 'clusters';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sites_county_id_fkey';
            columns: ['county_id'];
            isOneToOne: false;
            referencedRelation: 'counties';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sites_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sites_region_id_fkey';
            columns: ['region_id'];
            isOneToOne: false;
            referencedRelation: 'regions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sites_supervisor_id_fkey';
            columns: ['supervisor_id'];
            isOneToOne: false;
            referencedRelation: 'supervisors';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'sites_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      solar_readings: {
        Row: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          panels_installed: number | null;
          panels_operational: number | null;
          damaged_panel_count: number | null;
          charge_controller_output_v: number | null;
          panels_cleaned: boolean | null;
          system_operating_normally: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          visit_id: string;
          site_id: string;
          recorded_at: string;
          panels_installed?: number | null;
          panels_operational?: number | null;
          damaged_panel_count?: number | null;
          charge_controller_output_v?: number | null;
          panels_cleaned?: boolean | null;
          system_operating_normally?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          visit_id?: string;
          site_id?: string;
          recorded_at?: string;
          panels_installed?: number | null;
          panels_operational?: number | null;
          damaged_panel_count?: number | null;
          charge_controller_output_v?: number | null;
          panels_cleaned?: boolean | null;
          system_operating_normally?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'solar_readings_site_id_fkey';
            columns: ['site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'solar_readings_visit_id_fkey';
            columns: ['visit_id'];
            isOneToOne: true;
            referencedRelation: 'pm_visits';
            referencedColumns: ['id'];
          },
        ];
      };
      supervisors: {
        Row: {
          id: string;
          employee_code: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id: string;
          employee_code?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          employee_code?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'supervisors_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'supervisors_id_fkey';
            columns: ['id'];
            isOneToOne: true;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'supervisors_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      system_settings: {
        Row: {
          key: string;
          value: Json;
          description: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          key?: string;
          value?: Json;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'system_settings_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'system_settings_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      technicians: {
        Row: {
          id: string;
          employee_code: string | null;
          region_id: string | null;
          supervisor_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id: string;
          employee_code?: string | null;
          region_id?: string | null;
          supervisor_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          employee_code?: string | null;
          region_id?: string | null;
          supervisor_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'technicians_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'technicians_id_fkey';
            columns: ['id'];
            isOneToOne: true;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'technicians_region_id_fkey';
            columns: ['region_id'];
            isOneToOne: false;
            referencedRelation: 'regions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'technicians_supervisor_id_fkey';
            columns: ['supervisor_id'];
            isOneToOne: false;
            referencedRelation: 'supervisors';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'technicians_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      user_region_scopes: {
        Row: {
          profile_id: string;
          region_id: string;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          profile_id: string;
          region_id: string;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          profile_id?: string;
          region_id?: string;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'user_region_scopes_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'user_region_scopes_profile_id_fkey';
            columns: ['profile_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'user_region_scopes_region_id_fkey';
            columns: ['region_id'];
            isOneToOne: false;
            referencedRelation: 'regions';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      pm_schedule_overview: {
        Row: {
          id: string | null;
          site_id: string | null;
          site_code: string | null;
          site_name: string | null;
          region_id: string | null;
          county_id: string | null;
          is_demo: boolean | null;
          template_id: string | null;
          template_name: string | null;
          template_version: number | null;
          technician_id: string | null;
          technician_name: string | null;
          supervisor_id: string | null;
          supervisor_name: string | null;
          frequency: Database['public']['Enums']['pm_frequency'] | null;
          scheduled_date: string | null;
          due_date: string | null;
          status: Database['public']['Enums']['pm_status'] | null;
          is_overdue: boolean | null;
          priority: Database['public']['Enums']['priority_level'] | null;
          notes: string | null;
          visit_id: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Relationships: [];
      };
      pm_visit_overview: {
        Row: {
          id: string | null;
          schedule_id: string | null;
          site_id: string | null;
          site_code: string | null;
          site_name: string | null;
          region_id: string | null;
          county_id: string | null;
          template_id: string | null;
          template_version: number | null;
          technician_id: string | null;
          technician_name: string | null;
          supervisor_id: string | null;
          supervisor_name: string | null;
          status: Database['public']['Enums']['pm_status'] | null;
          started_at: string | null;
          ended_at: string | null;
          submitted_at: string | null;
          reviewed_at: string | null;
          reviewed_by_name: string | null;
          review_comments: string | null;
          completion_pct: number | null;
          failure_count: number | null;
          gps_status: Database['public']['Enums']['gps_status'] | null;
          is_demo: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Relationships: [];
      };
      site_overview: {
        Row: {
          id: string | null;
          site_code: string | null;
          site_name: string | null;
          status: Database['public']['Enums']['site_status'] | null;
          is_demo: boolean | null;
          site_type: string | null;
          power_configuration: string | null;
          generator_available: boolean | null;
          solar_available: boolean | null;
          battery_available: boolean | null;
          grid_available: boolean | null;
          latitude: number | null;
          longitude: number | null;
          address: string | null;
          geofence_radius_m: number | null;
          region_id: string | null;
          region_name: string | null;
          cluster_id: string | null;
          cluster_name: string | null;
          county_id: string | null;
          county_name: string | null;
          supervisor_id: string | null;
          supervisor_name: string | null;
          technician_names: string | null;
          last_pm_at: string | null;
          next_pm_due: string | null;
          next_pm_status: Database['public']['Enums']['pm_status'] | null;
          open_failures: number | null;
          open_corrective_actions: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Relationships: [];
      };
      supervisor_overview: {
        Row: {
          id: string | null;
          full_name: string | null;
          email: string | null;
          phone: string | null;
          employee_code: string | null;
          is_active: boolean | null;
          region_names: string | null;
          county_names: string | null;
          site_count: number | null;
          technician_count: number | null;
        };
        Relationships: [];
      };
      technician_overview: {
        Row: {
          id: string | null;
          full_name: string | null;
          email: string | null;
          phone: string | null;
          employee_code: string | null;
          is_active: boolean | null;
          region_id: string | null;
          region_name: string | null;
          supervisor_id: string | null;
          supervisor_name: string | null;
          assigned_sites: number | null;
          open_pm: number | null;
          overdue_pm: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      admin_activate_template: {
        Args: {
          p_template_id: string;
        };
        Returns: undefined;
      };
      admin_clone_template: {
        Args: {
          p_template_id: string;
        };
        Returns: string;
      };
      admin_set_region_scopes: {
        Args: {
          p_user_id: string;
          p_region_ids: string[];
        };
        Returns: undefined;
      };
      admin_update_user: {
        Args: {
          p_user_id: string;
          p_role: Database['public']['Enums']['app_role'];
          p_is_active: boolean;
          p_region_id?: string;
        };
        Returns: Database['public']['Tables']['profiles']['Row'];
      };
      mark_overdue_schedules: {
        Args: never;
        Returns: number;
      };
      mobile_sync_bundle: {
        Args: never;
        Returns: Json;
      };
      pm_visit_issues: {
        Args: {
          p_visit_id: string;
        };
        Returns: { section_code: string; ref_type: string; ref_id: string; label: string; issue: string }[];
      };
      record_login: {
        Args: {
          p_client?: string;
        };
        Returns: undefined;
      };
      record_report_generated: {
        Args: {
          p_report: string;
          p_filters?: Json;
          p_row_count?: number;
        };
        Returns: undefined;
      };
    };
    Enums: {
      app_role: 'super_admin' | 'regional_manager' | 'regional_supervisor' | 'technician' | 'maintenance' | 'viewer';
      corrective_action_status: 'OPEN' | 'ASSIGNED' | 'IN_PROGRESS' | 'COMPLETED' | 'VERIFIED' | 'CLOSED';
      failure_source: 'PM_CHECKLIST' | 'MANUAL';
      failure_status: 'OPEN' | 'ASSIGNED' | 'IN_PROGRESS' | 'RESOLVED' | 'VERIFIED' | 'CLOSED';
      geofence_mode: 'WARN' | 'REQUIRE_REASON' | 'BLOCK';
      gps_status: 'WITHIN_RADIUS' | 'OUTSIDE_RADIUS' | 'UNAVAILABLE' | 'SITE_HAS_NO_COORDINATES';
      notification_type: 'PM_OVERDUE' | 'PM_COMPLETED' | 'PM_SUBMITTED' | 'PM_APPROVED' | 'PM_REJECTED' | 'PM_SCHEDULED' | 'PM_DUE' | 'SITE_ASSIGNED' | 'CRITICAL_FAILURE' | 'CORRECTIVE_ACTION_ASSIGNED' | 'CORRECTIVE_ACTION_OVERDUE' | 'CORRECTIVE_ACTION_COMPLETED';
      pm_category: 'GENERATOR' | 'DC_SYSTEM' | 'BATTERY' | 'SOLAR' | 'NON_TECHNICAL' | 'EARTHING';
      pm_frequency: 'WEEKLY' | 'BIWEEKLY' | 'MONTHLY' | 'BIMONTHLY' | 'QUARTERLY' | 'SEMIANNUAL' | 'ANNUAL' | 'AD_HOC';
      pm_status: 'SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'SUBMITTED' | 'APPROVED' | 'REJECTED' | 'OVERDUE' | 'CANCELLED';
      priority_level: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
      response_type: 'YES_NO_NA' | 'NUMBER' | 'TEXT' | 'SELECT' | 'MULTI_SELECT' | 'PHOTO' | 'DATE' | 'DATETIME';
      severity_level: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
      site_status: 'ACTIVE' | 'INACTIVE' | 'DECOMMISSIONED';
      template_status: 'DRAFT' | 'ACTIVE' | 'RETIRED';
      yes_no_na: 'YES' | 'NO' | 'N/A';
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database['public'];
type PublicTablesAndViews = PublicSchema['Tables'] & PublicSchema['Views'];
/** Row type of a table or view. */
export type Tables<T extends keyof PublicTablesAndViews> = PublicTablesAndViews[T]['Row'];
export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update'];
export type Enums<T extends keyof PublicSchema['Enums']> = PublicSchema['Enums'][T];

export const Constants = {
  public: {
    Enums: {
      app_role: ['super_admin', 'regional_manager', 'regional_supervisor', 'technician', 'maintenance', 'viewer'],
      corrective_action_status: ['OPEN', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'CLOSED'],
      failure_source: ['PM_CHECKLIST', 'MANUAL'],
      failure_status: ['OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'VERIFIED', 'CLOSED'],
      geofence_mode: ['WARN', 'REQUIRE_REASON', 'BLOCK'],
      gps_status: ['WITHIN_RADIUS', 'OUTSIDE_RADIUS', 'UNAVAILABLE', 'SITE_HAS_NO_COORDINATES'],
      notification_type: ['PM_OVERDUE', 'PM_COMPLETED', 'PM_SUBMITTED', 'PM_APPROVED', 'PM_REJECTED', 'PM_SCHEDULED', 'PM_DUE', 'SITE_ASSIGNED', 'CRITICAL_FAILURE', 'CORRECTIVE_ACTION_ASSIGNED', 'CORRECTIVE_ACTION_OVERDUE', 'CORRECTIVE_ACTION_COMPLETED'],
      pm_category: ['GENERATOR', 'DC_SYSTEM', 'BATTERY', 'SOLAR', 'NON_TECHNICAL', 'EARTHING'],
      pm_frequency: ['WEEKLY', 'BIWEEKLY', 'MONTHLY', 'BIMONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'ANNUAL', 'AD_HOC'],
      pm_status: ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'OVERDUE', 'CANCELLED'],
      priority_level: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
      response_type: ['YES_NO_NA', 'NUMBER', 'TEXT', 'SELECT', 'MULTI_SELECT', 'PHOTO', 'DATE', 'DATETIME'],
      severity_level: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
      site_status: ['ACTIVE', 'INACTIVE', 'DECOMMISSIONED'],
      template_status: ['DRAFT', 'ACTIVE', 'RETIRED'],
      yes_no_na: ['YES', 'NO', 'N/A'],
    },
  },
} as const;
